@WebApplication1_HostAddress = https://localhost:7232

GET {{WebApplication1_HostAddress}}/Persons

###

PUT {{WebApplication1_HostAddress}}/Persons/1
Content-Type: application/json

{
    "name": "John Doe updated",
    "companies": [
      {
        "id": 1,
        "companyId": 1,
        "name": "Acme Corp updated",
        "fromDate": "2020-01-01T00:00:00",
        "toDate": null,
        "concurrencyToken": "AAAAAAAAD6U="
      },
      {
        "id": 2,
        "companyId": 2,
        "name": "Globex Inc",
        "fromDate": "2020-01-01T00:00:00",
        "toDate": null,
        "concurrencyToken": "AAAAAAAAD6Y="
      }
    ],
    "concurrencyToken": "AAAAAAAAD6M="
  }

###

GET {{WebApplication1_HostAddress}}/Companies

###

POST {{WebApplication1_HostAddress}}/Companies
Content-Type: application/json

{
    "name": "Added company",
    "fromDate": "2020-01-01T00:00:00",
    "toDate": null
    }
###

PUT {{WebApplication1_HostAddress}}/Persons/1
Content-Type: application/json

{
    "name": "John Doe updated again",
    "companies": [
      {
        "id": 1,
        "companyId": 1,
        "name": "Acme Corp updated again",
        "fromDate": "2020-01-01T00:00:00",
        "toDate": null,
        "concurrencyToken": "AAAAAAAAD6k="
      },
      {
        "companyId": 3,
        "fromDate": "2020-01-01T00:00:00",
        "toDate": null
      }
    ],
    "concurrencyToken": "AAAAAAAAD6s="
  }

###

POST {{WebApplication1_HostAddress}}/Persons/2/Companies
Content-Type: application/json

{
  "companyIds": [1, 2],
  "concurrencyToken": "AAAAAAAAD6Q="
}

###

POST {{WebApplication1_HostAddress}}/Persons/2/Companies
Content-Type: application/json

{
  "companyIds": [1],
  "concurrencyToken": "AAAAAAAAD6k="
}
